platform :ios
target 'MT_NuoMi' do  
pod 'Reachability',  '~> 3.0.0'    


platform :ios, '7.0'

pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVProgressHUD'
pod 'KVOController'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'Mantle'

pod 'WebViewJavascriptBridge'
end
